### ISSUE TITLE
网络请求超时啊

### ISSUE THREAD

**Issue by zychen2016** [qktechies/icourses#1]
不管是迅雷还是aria2

**Comment by David-Lin** [comment]
网络请求超时+1

**Comment by qktechies** [comment]
> 不管是迅雷还是aria2



> 网络请求超时+1
之前接口加入了10s的超时时间

**Comment by qktechies** [comment]
> 不管是迅雷还是aria2

之前接口加入了10s的超时时间，爱课程网的接口请求超过10s了



> 网络请求超时+1

之前接口加入了10s的超时时间，爱课程网的接口请求超过10s了
